### ISSUE TITLE
useKeys hooks for listening to one or multiple keypresses

### ISSUE THREAD

**Issue by simbathesailor** [imbhargav5/rooks#62] opened 2019-04-14 11:04 UTC
Feature

useKeys hooks allow adding certain action when one or multiple keys are pressed at the same time.

I have picked up the task of creating this hook.

I will be using this ticket for the questions and track the progress of this specific hook.

**Comment by simbathesailor** [comment] 2019-04-14 11:09
@imbhargav5 Shall I cut the new branch from dev branch ?

**Comment by imbhargav5** [comment] 2019-04-14 11:25
Hi @simbathesailor You can base of master. I have already merged dev branch into master. :)

**Comment by simbathesailor** [comment] 2019-04-15 04:38
I implemented the working useKeysHook. So it basically works but doesn't work :). Here is the link for codepen where I am using the useKeysHook which I will be committing. 

https://codepen.io/stack26/pen/BEwJqx?editors=1011

So how can I make sure the callback takes the updated value. In my case, i am looking for "testValue" variable that should get updated in the callback.
I tried setting it to ref also but, I think something I am missing.  Any suggestions ?

**Comment by imbhargav5** [comment] 2019-04-15 07:51
Do you mind creating a codesandbox link instead? Codepen is notoriously difficult for viewing large js files haha. Took a look but looks like `useRef` wasn't used to maintain ref to the current callback. I think that is the reason.

**Comment by simbathesailor** [comment] 2019-04-15 13:53
Yes, you are right, didn't think that the code will become so big. :). Here is the codesand box link:
https://codesandbox.io/s/zq6mm0nykp . I tried adding ref to callback also, but it didn't seem to work.
Something it seems I am not clear about these hooks

**Comment by imbhargav5** [comment] 2019-04-15 16:14
Oh, how can I reproduce the bug?

**Comment by simbathesailor** [comment] 2019-04-15 16:15
See the codesandbox link, there I have logged testValue in one of the callback. It should console the updated testValue, but it doesnot !!

**Comment by imbhargav5** [comment] 2019-04-15 16:33
Ah.. so some of the logic is against the hooks spec. For eg: you cannot have one hook within another. So `useKeyDown` within `useEffect` is wrong.

**Comment by simbathesailor** [comment] 2019-04-15 16:53
you are right, now it seems to work, https://codesandbox.io/s/p9q7q1l8y7. But it triggers a thought that will it not be problematic to write interdependent hook more that one level ?  💭 

Does everything look ok with the code now or you want to discuss anything, that we might change ? 🤔

**Comment by imbhargav5** [comment] 2019-04-15 17:49
So, I think it can be a lot less complicated than that to be honest. I think it can look at lot similar to useKeys with minor changes to make it multi.

**Comment by simbathesailor** [comment] 2019-04-16 06:33
Hmm. you are right there. Made some changes after having a look at useKey.  https://codesandbox.io/s/p9q7q1l8y7
Now the API look like :

```
useKeys(
    ["ControlLeft", "S"],
    event => {
      // Custom logic for handler
    },
    {
      target: documentRef
    }
  );
```

I have made use of event.code as the key array. Reson being small case and capital cases are same for this usecase. ctrl, alt, option like keys which are mostly two in keypads.Differtentiating betwen small case, uppercase, left , right buttons  using event.key, event.location seemed not good. Using event.code will give the consumer of the hook to add letters, ControlLeft, AltLeft directly.

I had some issue with typescript. Can you have a look at it useKeys line 80. some typescript error is happening and i am having a hard time fixing it.
After this i will try to raise pr and there we can review the code.

**Comment by simbathesailor** [comment] 2019-04-18 16:23
Do let me know how it looks if by any chance you had the time to look at it.  Then we can finalize it. 

Also I wanted to know what are the check point before raising the pr ??

Like what kind of test cases are required ?
Documenation ?
Code comments doc blocks ?

**Comment by simbathesailor** [comment] 2019-05-19 09:36
https://github.com/imbhargav5/rooks/pull/65

**Closed** 2019-08-03 11:50 UTC
Labels: disccussion 🗣️
